package Gravity;

import cpw.mods.fml.client.FMLClientHandler;
import cpw.mods.fml.common.*;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.eventhandler.EventBus;
import cpw.mods.fml.common.gameevent.TickEvent;
import cpw.mods.fml.common.registry.GameRegistry;
//import grim3212.mc.core.Grim3212Core;
//import grim3212.mc.core.GrimModule;
//import grim3212.mc.core.util.VersionChecker;
import java.util.List;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiIngame;
import net.minecraft.client.gui.GuiNewChat;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ChatComponentText;

// Referenced classes of package grim3212.mc.gravitycontrol:
//            ItemGravityController, ItemLowGravityController, ItemGravityAnchor

public class GravityControl extends GrimModule
{

    public GravityControl()
    {
    }

    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.version = "V0.1 - 1.7.2";
        data.name = "Gravity Controller";
        data.description = "Allows you to control gravity.";
        data.authorList.add("Grim3212");
        data.authorList.add("dude0367");
        data.url = "http://grim3212.wikispaces.com/Gravity+Control";
        data.credits = "Thanks to dude0367 for the original mod.";
        data.logoFile = "assets/grim3212-logo-texture/grimLogo.png";
        ItemGravityController = (new ItemGravityController()).func_77637_a(Grim3212Core.tabsGrimItems).func_77655_b("GravityController").func_77625_d(1).func_111206_d("gravitycontrol:gravcontroller");
        ItemLowGravityController = (new ItemLowGravityController()).func_77637_a(Grim3212Core.tabsGrimItems).func_77655_b("LowGravityController").func_77625_d(1).func_111206_d("gravitycontrol:lowgravcontroller");
        ItemGravityAnchor = (new ItemGravityAnchor()).func_77637_a(Grim3212Core.tabsGrimItems).func_77655_b("GravityAnchor").func_77625_d(1).func_111206_d("gravitycontrol:gravityanchor");
        GameRegistry.registerItem(ItemGravityController, ItemGravityController.func_77658_a(), "gravitycontrol");
        GameRegistry.registerItem(ItemLowGravityController, ItemLowGravityController.func_77658_a(), "gravitycontrol");
        GameRegistry.registerItem(ItemGravityAnchor, ItemGravityAnchor.func_77658_a(), "gravitycontrol");
        GameRegistry.addShapedRecipe(new ItemStack(ItemGravityController, 1), new Object[] {
            "EGE", "GDG", "EGE", Character.valueOf('G'), Items.field_151043_k, Character.valueOf('E'), Items.field_151061_bv, Character.valueOf('D'), Items.field_151045_i
        });
        GameRegistry.addShapedRecipe(new ItemStack(ItemLowGravityController, 1), new Object[] {
            "EGE", "GDG", "EGE", Character.valueOf('G'), Items.field_151043_k, Character.valueOf('E'), Items.field_151079_bi, Character.valueOf('D'), Items.field_151045_i
        });
        GameRegistry.addShapedRecipe(new ItemStack(ItemGravityAnchor, 1), new Object[] {
            " O ", " O ", "III", Character.valueOf('O'), Blocks.field_150343_Z, Character.valueOf('I'), Blocks.field_150339_S
        });
    }

    public void load(FMLInitializationEvent event)
    {
        FMLCommonHandler.instance().bus().register(this);
        if(Grim3212Core.doUpdateCheck)
        {
            GravityControl _tmp = this;
            versionChecker = new VersionChecker("Gravity Controller", "V0.1 - 1.7.2", versionUrl, "http://grim3212.wikispaces.com/Gravity+Control");
            versionChecker.checkVersionWithLoggingBySubStringAsFloat(1, 4);
        }
    }

    public void tick(cpw.mods.fml.common.gameevent.TickEvent.ClientTickEvent event)
    {
        if(FMLClientHandler.instance().getClient().field_71462_r == null && Grim3212Core.doUpdateCheck)
        {
            GravityControl _tmp = this;
            if(canVersionCheck && !versionChecker.isCurrentVersionBySubStringAsFloatNewer(1, 4))
            {
                String arr$[] = versionChecker.getInGameMessage();
                int len$ = arr$.length;
                for(int i$ = 0; i$ < len$; i$++)
                {
                    String msg = arr$[i$];
                    FMLClientHandler.instance().getClient().field_71456_v.func_146158_b().func_146227_a(new ChatComponentText(msg));
                }

                GravityControl _tmp1 = this;
                canVersionCheck = false;
            }
        }
    }

    public String getModID()
    {
        return "gravitycontrol";
    }

    public static GravityControl instance;
    public static final String modID = "gravitycontrol";
    public static final String modName = "Gravity Controller";
    public static final String modVersion = "V0.1 - 1.7.2";
    public static final String modURL = "http://grim3212.wikispaces.com/Gravity+Control";
    private static VersionChecker versionChecker;
    public static boolean canVersionCheck = true;
    public static Item ItemGravityController;
    public static Item ItemGravityAnchor;
    public static Item ItemLowGravityController;

}
